### ISSUE TITLE
CMAutoEditor Just closes

### ISSUE THREAD

**Issue by Lorenzo6677** [DerButschi/CMAutoEditor#18]
**Describe the bug**
When asking CMAuto Editor to run map creation from a csv file (converted from OSM data) set using bounding box, the editor window just closes.

**To Reproduce**
Downloaded data from OSM (irrelevant whether from UK, Poland or Germany)
Converted from Geojson to CM using any profile, and using 'Take Bounding Box from OSM data'
Ran CM Auto Editor, using the relevant CSV

**Setup:**
 - OS: Windows 10 Home 64 bit
 - Python distribution: unsure
 - CMAutoEditor version: 2.1 release

**Screenshot**
CMAutoEdit auto closes before screenshot can be grabbed

**Additional context**
Using either profile, even using the point setter through armymap method seems to result in the autoedit just closing. Have also tried using admin but still autocloses.

**Comment by DerButschi** [comment]
Can you please attach (one of) the input csv-File(s)?

**Comment by Lorenzo6677** [comment]
[germanvillage.csv](https://github.com/DerButschi/CMAutoEditor/files/11398542/germanvillage.csv)

**Comment by DerButschi** [comment]
Thanks, I can reproduce the issue. Looks like the packaging got messed up.

**Comment by Lorenzo6677** [comment]
Initial test done, window doesn't immediately close, will test again when I have the chance later today to give you a concrete answer.

**Comment by Lorenzo6677** [comment]
Fully tested in CM:CW
Issue is now resolved
