### ISSUE TITLE
dgm2cm crash, TypeError: '<' not supported between instances of 'str' and 'float'

### ISSUE THREAD

**Issue by HeirloomTomato** [DerButschi/CMAutoEditor#23]
**Describe the bug**
I am trying to use the DGMtoCM program to convert an xyz file to be usable by the autoeditor. I converted a .tif file to xyz data using Qgis and following along with the youtube video you made. When I enter in the data the program starts and then closes. 

**Setup:**
 I am running windows 11 and using the latest release run from the download.
 I have included a screen shot of the process I used as well as attaching the xyz file. I posted a dropbox link as the xyz file was too large to upload.
https://www.dropbox.com/s/ljudwjn3seau4j4/Buggy.zip?dl=0

Hope this helps.

**Comment by DerButschi** [comment]
Hm, works perfectly ok on my machine... though as you can see in the image, you have selected a too large area for the data you have.

Can you please make a screenshot of the actual error message? If you start dgm2cm.exe from the Command Prompt, the Window will stay open after the crash.

![Perthstesty_orig](https://github.com/DerButschi/CMAutoEditor/assets/114301795/601790cf-010d-45eb-b15f-2c36dedef7d2)

**Comment by HeirloomTomato** [comment]
<img width="896" alt="Desktop Screenshot 2023 05 27 - 00 57 12 71" src="https://github.com/DerButschi/CMAutoEditor/assets/134669874/75dfc45e-aad6-4610-86d0-4298ed3c1e18">
Here is the screenshot of the command prompt when it failed for me this time.

**Comment by DerButschi** [comment]
Ah, do you have your xyz file in a separate folder? If not, please try that. Make an empty folder and only put that xyz file (or files if you happen to have more than one) in there and no files of other types (e.g. your file with .aux). It looks like the tool is reading data that is not xyz and consequently fails to process it.

**Comment by Pinetree74** [comment]
I had that exact same error but I'm pretty sure mine was from trying to use a xyz file that had only been converted from a 8 metre resolution file (I was experimenting). Take a look and make sure you reprojected the geotiff to 1m before converting it to xyz.

**Comment by DerButschi** [comment]
> I had that exact same error but I'm pretty sure mine was from trying to use a xyz file that had only been converted from a 8 metre resolution file (I was experimenting). Take a look and make sure you reprojected the geotiff to 1m before converting it to xyz.

As you can see from my plot above, the xyz data itself was ok, I could process it without problems. But I did move the file to a separate folder.

**Comment by DerButschi** [comment]
> Actually, looking in the folder there was an aux.xml file in the folder as well. deleting it has allowed the tool to work correctly with an 8m res file

Yes, the data itself is ok, but you have to make sure that it is just the data and nothing else in the folder.

**Comment by HeirloomTomato** [comment]
When I removed the aux.xml file the program worked! Thanks for the solution.

**Comment by DerButschi** [comment]
Glad to hear! I'll make a mental note to either make it more clear or only read in the correct files.
