### ISSUE TITLE
OSM2CM bounding box option produces error

### ISSUE THREAD

**Issue by ArchieHill** [DerButschi/CMAutoEditor#26]
**Describe the bug**
When using the axis parallel bounding box option to define the OSM boundaries the program crashes with a uncaught ValueError: A linearring requires at least 4 coordinates on line 333 of the code. 

**To Reproduce**
1. Start osm2cm with no arguments so the UI shows up
2. Enter the details as shown in the screenshot
![image](https://github.com/DerButschi/CMAutoEditor/assets/94839295/31b4e363-4a8d-49d5-b3e8-9cc099a3a802)
3. Start osm2cm

**Setup:**
 - OS: Windows 10
 - (if applicable, i.e. if you didn't use the .exe files) Python distribution: Vscode with python extension and pip
 - CMAutoEditor version: manually installed from latest pull of master (28/10/2023)

**Screenshot**
![image](https://github.com/DerButschi/CMAutoEditor/assets/94839295/1c439b75-65cb-47f0-a2c2-c739b68078c5)

**Additional context**
I've attached the geojson file to the issue, Github doesn't support uploading it in the geojson format however, so I just renamed the extension to json. Changing the extension back to geojson should work again.

[map.json](https://github.com/DerButschi/CMAutoEditor/files/13196482/map.json)

**Comment by DerButschi** [comment]
Thanks for bringing this one up. Should be fixed now. Could you please try?

**Comment by ArchieHill** [comment]
[BadHersfeldOSM.csv](https://github.com/DerButschi/CMAutoEditor/files/13301377/BadHersfeldOSM.csv)

Reran with fix, it worked and produced the csv attached. Looking at the debug svgs it looks like it all worked perfectly.
