### ISSUE TITLE
Autoeditor not clicking on the maptiles

### ISSUE THREAD

**Issue by FRO71** [DerButschi/CMAutoEditor#28]
**Describe the bug**
Running the autoeditor the cursor wanders in the map editor from the map to the function buttons on the left of the screen, clicking there to finally accidentially start the 3D Map Preview, clicking to no avail for another 20min . The map remains unedited.

**To Reproduce**
applied all steps as explained in the youtube videos

**Setup:**
 - OS: Windows 10
 - did use the .exe files
 - CMAutoEditor version: 2.2 and thereafter 2.3

**Screenshot**
not available.

**Additional context**
Just a final remark. The CMAutoeditor is the best thing that ever happenend to this outstanding game. Much applause to its creator. It would realy kick-start my CM addiction if it would work also for me. So help is much appreciated.

**Comment by DerButschi** [comment]
Ok, guess I need some additional information. Would be easiest if you could make a video of the process. Can you describe more precisely what is happening? Like, which buttons does the cursor go to? 

What screen resolution are you running on? Do you use Windows 10 screen scaling? Are you running in a window (not sure that is even possible).

**Comment by FRO71** [comment]
Wow, thank you very much for hinting the screen scaling. That did the trick and I got the spectacular result of a realistic georeferenced terrain relief in CM. Outstanding! 
Unfortunately I afterwards got stuck while running the autoeditor to add the osm data to the map. The editor starts with adding woods to a portion of the map, then gets stuck when changing to the crops button. The cursor stays on the button without any further clicking and the whole process ends. When reviewing the 3D-Map there is only the small wooded area that was added at the start. What could be the problem here? A debug folder was created with files for streets, houses, churches etc. Any hints?

**Comment by DerButschi** [comment]
We'll get there, eventually. ;-)

Again, you'll have to provide me with more details, though (my telepathic abilities are embarassingly underdeveloped, I'm afraid).

- How did you actually solve the Windows scaling problem? Did you switch it off? 
- What parameters did you set for CMAutoEditor, please provide a screenshot (yes, I need screenshots!)
- Did you run on the map containing the elevations (so a pre-existing map) or on a fresh map? How the former, how?
- Did the process terminate normally (i.e. with the corresponding message?)
- Can you provide a screenshot or video of the cursor "staying on the button"?
- Can you provide the .csv file you use as input?
- ...

Really, please answer this systematically and with as much detail as possible.

**Comment by FRO71** [comment]
Again, thanks a lot for digging into my problems here.
To answer your questions:

- I switched the screen scaling in the settings which was as recommended on 200% back to 100% and thus the elevation editing was flawless.
- Parameters and cursor behaviour can be seen in the pictures attached.
- I sure did run the osm-editing on the pre-existing elevation map. The original map size is 3072X1344. When checking the box for "Take start size from file" the map is reduced in the process to 208X208.
- The process does not terminate normally. After promisingly editing trees to the small map thats left,
 the cursor stops on the "clover" button without any further clicking or ending message. 
- The .csv file is attached. I did run the osm2cm-process once using the grid-file and once entering the coordinates of the bounding box with the same result when running the AutoEditor.

When creating the *csv file using osm2cm a folder named "debug" was created which contains a number of HTML-Documents named "buildings_houses", or "path_search_road". Are these sort of error-messages concerning the osm-data-translation?

I keep my fingers crossed that this information can help to solve the problem.

![01-Parameters of CMAutoEditor](https://github.com/DerButschi/CMAutoEditor/assets/152012828/cd9681cb-651e-4dec-b6fc-2d2754558de8)
![02-Start on the existing elevation map](https://github.com/DerButschi/CMAutoEditor/assets/152012828/67c289a7-4426-4635-b0fb-7e25f408f822)
![03-Autoedited reduced map size](https://github.com/DerButschi/CMAutoEditor/assets/152012828/1b7600b5-8c7f-4ad6-8617-25ac513845e0)
![04-End of the editing process](https://github.com/DerButschi/CMAutoEditor/assets/152012828/b59b3181-2a6f-4215-89e0-1c9a8ec2e0f3)
[St_Vith_1_osm.csv](https://github.com/DerButschi/CMAutoEditor/files/13491647/St_Vith_1_osm.csv)

**Comment by DerButschi** [comment]
Thanks! Alright, I was able to reproduce and (hopefully fix) the problem. Please try https://github.com/DerButschi/CMAutoEditor/releases/edit/2.3.1-beta1.

**Comment by DerButschi** [comment]
*bump*
Does it work?

**Comment by DerButschi** [comment]
Great! Happy to help. :-)
